name: Create release pull request
# Must manually add the label `skip-changelog` to the repository before running this workflow.

on:
  workflow_dispatch:

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Get draft release version
        uses: cardinalby/git-get-release-action@v1
        with:
          latest: true
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: get-draft-release
        # Fail this step if not found draft release

      - name: Generate next version number (remove prefix)
        run: |
          version="$(echo ${{ steps.get-draft-release.outputs.tag_name }} | sed -r 's/^.*([0-9]+\.[0-9]+\.[0-9]+[0-9a-z\-\+]*)/\1/')"
          echo "::set-output name=version::$version"
        id: next-version

      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Bump version and create pull-request
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b release/${{ steps.next-version.outputs.version }}
          npm version --no-git-tag-version ${{ steps.next-version.outputs.version }}
          git add .
          git commit -m"Bump version to v${{ steps.next-version.outputs.version }}"
          git push origin HEAD
          gh pr create --fill --label "skip-changelog"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
