name: Create release pull request

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number (without prefix)'
        required: true
        default: ''

jobs:
  create_release_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: |
          git checkout -b release/${{ github.event.inputs.version }}
          npm version --no-git-tag-version ${{ github.event.inputs.version }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m"Bump version"
          git push origin HEAD
          gh pr create --fill
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
