name: Create release pull request
# Label `skip-changelog` must be added manually before running this workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number (without prefix)'
        required: true

jobs:
  create_release_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b release/${{ github.event.inputs.version }}
          npm version --no-git-tag-version ${{ github.event.inputs.version }}
          git add .
          git commit -m"Bump version to ${{ github.event.inputs.version }}"
          git push origin HEAD
          gh pr create --fill --label "skip-changelog"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
