# Copyright (c) 2021-2026 Koji Hasegawa.
# This software is released under the MIT License.

name: Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/test.yml'
  pull_request:
    types: [ opened, synchronize, reopened ]  # Same as default
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/test.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    if: github.event.pull_request.head.repo.fork == false # Skip on public fork, because can not read secrets.
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      checks: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        unityVersion: # Available versions see: https://game.ci/docs/docker/versions
          - 2019.4.41f2
          - 2022.3.62f3 # Non-Enterprise LTS
          - 6000.0.75f1
          - 6000.3.16f1
          - &latest_unity_version 6000.4.8f1
        include:
          - unityVersion: *latest_unity_version
            octocov: true

    steps:
      - name: Create project for test
        uses: nowsprinting/create-unity-project-action@95f60602e491564583a15ee611a21c23c2f5d5d4 # v4
        with:
          project-path: .

      - name: Get package checkout path
        run: |
          name=com.$(echo "${GITHUB_REPOSITORY}" | sed 's/\//\./g')
          echo "PACKAGE_PATH=$CREATED_PROJECT_PATH/Packages/$name" >> "$GITHUB_ENV"
          # In Linux editor, there is a problem that assets in local packages cannot be found with `AssetDatabase.FindAssets`.
          # As a workaround, I have made it into an embedded package.

      - name: Checkout repository as embedded package
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          submodules: false
          lfs: false
          path: ${{ env.PACKAGE_PATH }}

      - name: Install dependent UPM packages
        run: |
          npm install -g openupm-cli
          openupm add -f com.unity.test-framework@stable
        working-directory: ${{ env.CREATED_PROJECT_PATH }}

      - name: Install codecoverage package
        run: |
          openupm add -f com.unity.testtools.codecoverage
        working-directory: ${{ env.CREATED_PROJECT_PATH }}
        if: ${{ matrix.octocov }}

      - name: Restore cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ${{ env.CREATED_PROJECT_PATH }}/Library
          key: Library-${{ runner.os }}-${{ matrix.unityVersion }}-${{ hashFiles(format('{0}/package.json', env.PACKAGE_PATH)) }}
          restore-keys: |
            Library-${{ runner.os }}-${{ matrix.unityVersion }}-
            Library-${{ runner.os }}-
            Library-

      - name: Set coverage assembly filters
        run: |
          assemblies=$(find ${{ env.PACKAGE_PATH }} -name "*.asmdef" | sed -e s/.*\\//\+/ | sed -e s/\\.asmdef// | sed -e s/^.*\\.Tests//)
          # shellcheck disable=SC2001,SC2048,SC2086
          echo "assembly_filters=$(echo ${assemblies[*]} | sed -e s/\ /,/g),+<assets>,-*.Tests" >> "$GITHUB_ENV"
        if: ${{ matrix.octocov }}

      - name: Set license secret key
        run: echo "secret_key=UNITY_LICENSE_$(echo ${{ matrix.unityVersion }} | cut -c 1-4)" >> "$GITHUB_ENV"

      - name: Run tests
        uses: game-ci/unity-test-runner@0ff419b913a3630032cbe0de48a0099b5a9f0ed9 # v4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: ${{ matrix.unityVersion }}  # Default is `auto`
          checkName: test result (${{ matrix.unityVersion }})
          projectPath: ${{ env.CREATED_PROJECT_PATH }}
          customParameters: -retry 5 -testCategory "!IgnoreCI" -testHelperScreenshotDirectory /github/workspace/artifacts/Screenshots
          coverageOptions: generateAdditionalMetrics;generateTestReferences;generateHtmlReport;generateAdditionalReports;dontClear;assemblyFilters:${{ env.assembly_filters }}
          # see: https://docs.unity3d.com/Packages/com.unity.testtools.codecoverage@1.2/manual/CoverageBatchmode.html
        env:
          UNITY_LICENSE: ${{ secrets[env.secret_key] }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        id: test

      - name: Set coverage path for octocov
        run: |
          mv ${{ env.PACKAGE_PATH }}/.octocov.yml .
          sed -i -r 's/UnityProject~\/Logs/${{ steps.test.outputs.coveragePath }}/' .octocov.yml
        if: ${{ matrix.octocov }}

      - name: Run octocov
        uses: k1LoW/octocov-action@b3b6ee60482a667950f87553abf1df63217235d9 # v1
        if: ${{ matrix.octocov }}

      - name: Upload test results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: TestResults-Unity${{ matrix.unityVersion }}
          path: |
            ${{ steps.test.outputs.artifactsPath }}
            ${{ steps.test.outputs.coveragePath }}
        if: always()
